language: node_js
node_js:
- 10.12.0
sudo: required
dist: trusty
services:
- docker
before_install:
- docker pull minio/minio:latest
install:
- npm ci
script:
- npm run coverage
deploy:
  provider: npm
  on:
    tags: true
  api_key:
    secure: EAR8CPPDTtIRfbrNKtAdMgBVDCqRtrcjePgrMA/9Zf4RZZHTCYzKUmJtugeya4mXZvRbtgoty2g2bhrhjhNfa5oQXhZhfGFw7g+ZttCDGQ65pargFUnDaSC4pufLCr9unE1WUrCZtwwqgjkcqXAh7XYMqnz0cM39Wmo4O8ZEImqscYiLTQ7xUry6jjenPackhOfXhSqEwq4mC1MuOe2+CHHXV6irUZTACPgYYNPh8CmdeYcMxYTYMGLNAVl8ykNLiDdcTA2vPqUB8uU9pRrKYYDtyVgffb0MSEHuVxfc5W8ZSI0clK27m/bfgD5Nj7GHb/E7gepKWUblqgOPicOf9T2C1tUCgvMs2ySjHhjnrP9fGDhSV3E2xqThC7Wld3K3POXiy2YF6HdPSCg286CAGbmVGwoLeJcR+Zfa2vaOJyBTqVYlV5Hy8YVVgAjrDXDVo5ika7AlxqkUSHr6qRntyDXjjm/HNoV5C8jpTwwPDhed1E3ZfjSqEwMCxPo2bfdR5srBkTXqoBRwynw8pNr/TOn0RotXS4Wuc73qXwJbunxYP7wZ8Dxxd81ZHQdNQJl1p5c42Gwv1ZM1BV6GKogXgVfilj+wDJo0tmR5JeSIInF4f8azoRt6XRkueuGXj//LPXu8f3jKfHmU0mCTYVlV8gOtMWf+FzPkTviCsCjiBLk=
  email:
    secure: dZKLkH4ZbVVHHyh9lJ7UGkgNuf6s5jEyMK3nRh6BUvbPXpKWyGYt5LRPlWSP99yN20KsQ1VwEaTstpsznPczQDWP2oJZs7fhHjqASeyCYv+oI2ofwZPxTFfDRinpYOuvSE3juJyiCFVDc8H6Gc6fqt21sGYI8WeEPGTOBcnSGTcX+U8osjX5jWonCsuz4pejcA8MMNOIsk9ihdZjktzvQjUpMkbPFUvjz/2SZ6LrzCicY2dZSPV62W7u+TG69efDT4mL32+KpRvZ249pWSvlt7fquHhvMvedS7haHZj6t6XMJ7tgsebvs3ipvMlecVpsTGgfjbijw8EoXmjgq3Vnsmt4vt/xz9gyPMgyrNth6510WDj2mo/IP/1CeUVq3d7C1f9RG02QdUeUvkJA7fuZgorWyYwNZqc0q+s/zFSggD/DgtEHJwBz0QKjOcDmhZ8Q6UCp3K6NtEsZXgCf5Wg6NBkv7l+IufaBsJY5wMY3sAbUjj4vuKRc6FjxwovkyTQgs+w+HlFvgljN82FxE2bLZUBKJmqK6+l4knhPK4OfJK/J5mTusa9PwbEOMawesnMVsEjuFW8jxxQEmrL477QRD8MOWB6Jo8yuBFDGiDHCZ+mxJQ0eURqKvuPEUd26+IYpeBsKYm79EoK0R7Hmk9GgVBn4zNwp8HO4ZUSMThFCl6o=
